name: tests
on:
  push: 
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.linq'
  workflow_dispatch:

jobs:
  unit-test-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Extra step for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          ldd /home/runner/work/Sdcb.WordCloud/Sdcb.WordCloud/Sdcb.WordCloud.Tests/bin/Release/net8.0/libSkiaSharp.so
      - uses: actions/checkout@v4
      - name: Build code
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal