name: tests
on:
  push: 
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.linq'
  workflow_dispatch:

jobs:
  unit-test-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build code
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
      - name: show folder content
        run: ls -la
      - uses: actions/upload-artifact@v4
        with:
          name: integrated-test-${{ matrix.os }}
          path: ./Sdcb.WordCloud.Tests/bin/Release/net8.0/IntegratedTestOutput/